### ISSUE TITLE
data 수집에 관해서 여쭤보고 싶습니다!

### ISSUE THREAD

**Issue by jmh17360** [sonsuhyune/Pill_project#1]
안녕하세요! 저는 딥러닝 관련 강의를 수강하고 있는 대학교 4학년입니다.
제가 지금 final project로 간단한 딥러닝 application을 구현해 보는 것이 과제를 수행하고 있는데
비슷한 주제를 찾다가 이 글을 찾게 되었습니다.
제가 보기로는 알약을 크기, 각도 등을 달리하여 직접 사진을 찍으신 것 같은데,
혹시 많은 종류의 알약을 어떻게 구하셨는지 여쭤볼 수 있을까요!?

**Comment by sonsuhyune** [comment]
안녕하세요, 
아는 약사분을 통해 직접 알약을 수집하여 촬영하였습니다.
